apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-cells-labeled
  namespace: monitoring
  labels:
    app: nginx
    prometheus: kube-prometheus
spec:
  jobLabel: nginx-exporter
  selector:
    matchExpressions:
    - key: app.kubernetes.io/instance
      operator: In
      values: ["nginx-1", "nginx-2", "nginx-3"]
  namespaceSelector:
    matchNames:
    - nginx
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    relabelings:
    # Add cell label based on the service name
    - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
      regex: nginx-(\d+)
      targetLabel: cell
      replacement: $1
    # Add a human-readable cell name
    - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
      targetLabel: cell_name
    # Keep pod name for reference
    - sourceLabels: [__meta_kubernetes_pod_name]
      targetLabel: pod
    # Add namespace
    - sourceLabels: [__meta_kubernetes_namespace]
      targetLabel: namespace