apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-cells
  namespace: monitoring
  labels:
    app: nginx
    prometheus: kube-prometheus
spec:
  # This selector will match ALL services that have app=nginx-1, nginx-2, or nginx-3
  selector:
    matchExpressions:
    - key: app.kubernetes.io/instance
      operator: In
      values: ["nginx-1", "nginx-2", "nginx-3"]
  namespaceSelector:
    matchNames:
    - nginx
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    # These relabelings will extract the cell number from the service name
    relabelings:
    # Extract cell number from the instance label
    - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
      regex: nginx-(\d+)
      targetLabel: cell
      replacement: $1
    # Keep the original instance name as the job
    - sourceLabels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
      targetLabel: job