# Configuration for NGINX Cell 1
cell:
  id: "1"
  displayName: "Cell 1"

replicaCount: 1

customHtml:
  enabled: true
  themeColor: "#007bff"  # Blue theme for Cell 1

resources:
  nginx:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  exporter:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

serviceMonitor:
  enabled: false
  labels:
    prometheus: kube-prometheus
    cell: "1"

podDisruptionBudget:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true

# Anti-affinity to spread nginx-1 pods and avoid co-location with other nginx instances
affinity:
  podAntiAffinity:
    # Spread nginx-1 pods across different nodes
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nginx-1
        topologyKey: kubernetes.io/hostname
    # Required: Don't schedule on nodes that already have other nginx cells
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - nginx-cell
        - key: cell
          operator: NotIn
          values:
          - "1"
      topologyKey: kubernetes.io/hostname
