# Configuration for NGINX Cell 3
cell:
  id: "3"
  displayName: "Cell 3"

replicaCount: 1

customHtml:
  enabled: true
  themeColor: "#dc3545"  # Red theme for Cell 3

resources:
  nginx:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  exporter:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

serviceMonitor:
  enabled: false
  labels:
    prometheus: kube-prometheus
    cell: "3"

podDisruptionBudget:
  enabled: false

networkPolicy:
  enabled: false

autoscaling:
  enabled: false

affinity: {}