# Configuration for NGINX Cell 2
cell:
  id: "2"
  displayName: "Cell 2"

replicaCount: 1

customHtml:
  enabled: true
  themeColor: "#28a745"  # Green theme for Cell 2

resources:
  nginx:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  exporter:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

serviceMonitor:
  enabled: true
  labels:
    prometheus: kube-prometheus
    cell: "2"

podDisruptionBudget:
  enabled: false

networkPolicy:
  enabled: false

autoscaling:
  enabled: false

affinity: {}
