# Configuration for NGINX Cell 1
cell:
  id: "1"
  displayName: "Cell 1"

replicaCount: 1

customHtml:
  enabled: true
  themeColor: "#007bff"  # Blue theme for Cell 1

resources:
  nginx:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  exporter:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

serviceMonitor:
  enabled: true
  labels:
    prometheus: kube-prometheus
    cell: "1"

podDisruptionBudget:
  enabled: false

networkPolicy:
  enabled: false

autoscaling:
  enabled: false

affinity: {}
