# Configuration for NGINX Cell 2
cell:
  id: "2"
  displayName: "Cell 2"

replicaCount: 1

customHtml:
  enabled: true
  themeColor: "#28a745"  # Green theme for Cell 2

resources:
  nginx:
    limits:
      cpu: 150m
      memory: 192Mi
    requests:
      cpu: 75m
      memory: 96Mi
  exporter:
    limits:
      cpu: 50m
      memory: 64Mi
    requests:
      cpu: 10m
      memory: 32Mi

serviceMonitor:
  enabled: false
  labels:
    prometheus: kube-prometheus
    cell: "2"

podDisruptionBudget:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75

# Anti-affinity to spread nginx-2 pods and avoid co-location with other nginx instances
affinity:
  podAntiAffinity:
    # Spread nginx-2 pods across different nodes
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nginx-2
        topologyKey: kubernetes.io/hostname
    # Required: Don't schedule on nodes that already have other nginx cells
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - nginx-cell
        - key: cell
          operator: NotIn
          values:
          - "2"
      topologyKey: kubernetes.io/hostname
