apiVersion: v1
kind: Service
metadata:
  name: nginx-3
  namespace: nginx
  labels:
    app: nginx-3
    cell: "3"
spec:
  selector:
    app: nginx-3
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 9113
    targetPort: 9113
