apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "router.fullname" . }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["services", "endpoints"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "router.fullname" . }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "router.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "router.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
