{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "router.fullname" . }}-api-keys
  labels:
    {{- include "router.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-keys.json: |
    {
      {{- range $index, $item := .Values.auth.apiKeys }}
      {{- if $index }},{{ end }}
      {{ $item.key | quote }}: {{ $item.client | quote }}
      {{- end }}
    }
  {{- range $index, $item := .Values.auth.apiKeys }}
  api-key-{{ $index }}: {{ $item.key | quote }}
  {{- end }}
{{- end }}
