{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginx-cell.fullname" . }}
  labels:
    {{- include "nginx-cell.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "nginx-cell.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  ingress:
  {{- range .Values.networkPolicy.ingress }}
  - from:
    {{- toYaml .from | nindent 6 }}
    ports:
    - protocol: TCP
      port: 80
    {{- if $.Values.prometheusExporter.enabled }}
    - protocol: TCP
      port: 9113
    {{- end }}
  {{- end }}
{{- end }}
