apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-cell.fullname" . }}
  labels:
    {{- include "nginx-cell.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  {{- if .Values.prometheusExporter.enabled }}
  - port: {{ .Values.service.metricsPort }}
    targetPort: metrics
    protocol: TCP
    name: metrics
  {{- end }}
  selector:
    {{- include "nginx-cell.selectorLabels" . | nindent 4 }}
