configs:
  params:
    server.insecure: true
    controller.operation.processors: "5"
    controller.status.processors: "10"
    controller.self.heal.timeout.seconds: "10"
  cm:
    # Fix for Ingress health status
    resource.customizations.health.networking.k8s.io_Ingress: |
      hs = {}
      hs.status = "Healthy"
      return hs
    # Fix for ServiceMonitor health
    resource.customizations.health.monitoring.coreos.com_ServiceMonitor: |
      hs = {}
      hs.status = "Healthy"
      return hs
    # Increase timeout for large apps
    timeout.reconciliation: "180s"
    timeout.hard.reconciliation: "0s"

# Controller configuration
controller:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  parallelismLimit: 10

# Redis configuration
redis:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

# Server configuration
server:
  extraArgs:
    - --insecure
  service:
    type: NodePort
    nodePortHttp: 30080
    nodePortHttps: 30443
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi

# Repo server configuration
repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  parallelismLimit: 5

# Disable components we don't need
dex:
  enabled: false

applicationSet:
  enabled: false

notifications:
  enabled: false