apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: nginx-1
  app.kubernetes.io/instance: cell-1
  app.kubernetes.io/component: webserver
  app.kubernetes.io/part-of: cell-router
