apiVersion: v1
kind: Service
metadata:
  name: nginx-1
  namespace: nginx
  labels:
    app: nginx-1
    cell: "1"
spec:
  selector:
    app: nginx-1
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 9113
    targetPort: 9113
