apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 73.2.0
    helm:
      values: |
        # Minimal rules for Kind
        defaultRules:
          create: true
          rules:
            alertmanager: false
            etcd: false
            kubeScheduler: false
        
        # Prometheus configuration
        prometheus:
          prometheusSpec:
            retention: 24h
            resources:
              requests:
                cpu: 200m
                memory: 200Mi
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
        
        # Grafana configuration
        grafana:
          enabled: true
          adminPassword: admin
          service:
            type: NodePort
            nodePort: 30300
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          
          # Sidecar configuration for ConfigMap dashboards
          sidecar:
            datasources:
              enabled: true
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              # Search in all namespaces
              searchNamespace: ALL
          
          # Use default dashboards from the chart
          defaultDashboardsEnabled: true
          
          # Dashboard providers
          dashboardProviders:
            dashboardproviders.yaml:
              apiVersion: 1
              providers:
              - name: 'default'
                orgId: 1
                folder: ''
                type: file
                disableDeletion: false
                editable: true
                options:
                  path: /var/lib/grafana/dashboards/default
          
          # Community dashboards to import
          dashboards:
            default:
              nginx-exporter:
                gnetId: 12708
                revision: 1
                datasource: Prometheus
              kubernetes-cluster:
                gnetId: 7249
                revision: 1
                datasource: Prometheus
        
        # Disable components not needed in Kind
        kubeEtcd:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        
        # Minimal alertmanager
        alertmanager:
          enabled: true
          alertmanagerSpec:
            resources:
              requests:
                cpu: 50m
                memory: 50Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-dashboards
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/keepkipod/router.git
    targetRevision: HEAD
    path: k8s/monitoring
    directory:
      include: 'grafana-*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-rules
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/keepkipod/router.git
    targetRevision: HEAD
    path: k8s/monitoring
    directory:
      include: 'prometheus-rules-*.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false