apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 56.0.0
    helm:
      values: |
        # Minimal configuration for Kind
        defaultRules:
          create: true
          rules:
            alertmanager: true
            etcd: false
            kubeScheduler: false
        
        prometheus:
          prometheusSpec:
            retention: 24h
            resources:
              requests:
                cpu: 200m
                memory: 200Mi
              limits:
                cpu: 500m
                memory: 512Mi
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
        
        grafana:
          enabled: true
          adminPassword: admin
          service:
            type: NodePort
            nodePort: 30300
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        
        # Disable components not needed
        kubeEtcd:
          enabled: false
        kubeControllerManager:
          enabled: false
        kubeScheduler:
          enabled: false
        
        alertmanager:
          alertmanagerSpec:
            resources:
              requests:
                cpu: 50m
                memory: 50Mi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true