apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-2
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/keepkipod/router.git
    targetRevision: HEAD
    path: k8s/nginx/nginx-2
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true