apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-cells
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cell: "1"
            theme: "#007bff"
            replicas: "1"
          - cell: "2"
            theme: "#28a745"
            replicas: "1"
          - cell: "3"
            theme: "#dc3545"
            replicas: "1"
  template:
    metadata:
      name: 'nginx-{{cell}}'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      labels:
        app.kubernetes.io/part-of: cell-router
        app.kubernetes.io/component: nginx-cell
        cell: '{{cell}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/keepkipod/router.git
        targetRevision: HEAD
        path: k8s/nginx-helm
        helm:
          releaseName: 'nginx-{{cell}}'
          valueFiles:
            - 'values-cell-{{cell}}.yaml'
          parameters:
            - name: cell.id
              value: '{{cell}}'
            - name: replicaCount
              value: '{{replicas}}'
            - name: customHtml.themeColor
              value: '{{theme}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: nginx
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        retry:
          limit: 3
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 1m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
      revisionHistoryLimit: 10
      ignoreDifferences: []
      info:
        - name: "dependency"
          value: "ingress-nginx"