apiVersion: v1
kind: Service
metadata:
  name: nginx-2
  namespace: nginx
  labels:
    app: nginx-2
    cell: "2"
spec:
  selector:
    app: nginx-2
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: metrics
    port: 9113
    targetPort: 9113
